### ISSUE TITLE
mypyls on macosx doesn't install

### ISSUE THREAD

**Issue by ghost** [PythonNut/emacs-config#145]
Hello, 
emac downloads and extract however still asks to install mypyls

    (let ((system-ls "/usr/lib/microsoft-python-language-server/")
          (system-ls-bin (executable-find "mspyls")))
      (if (and (file-directory-p system-ls) system-ls-bin)
          (setq lsp-python-ms-dir system-ls
                lsp-python-ms-executable system-ls-bin)
        (setq lsp-python-ms-dir
              (locate-user-emacs-file "data/mspyls")      ;;;; osx; when removed work with bugs
              lsp-python-ms-executable
              (concat lsp-python-ms-dir
                      "Microsoft.Python.LanguageServer"
                      (and (eq system-type 'windows-nt) ".exe")))))

**Comment by PythonNut** [comment]
Hmm sorry I don't use macOS much anymore. Is the issue that Emacs downloads mspyls to the wrong place, or is it that the config is looking in the wrong place?

By the way, it's super interesting to me that other people are trying out this config!

**Comment by PythonNut** [comment]
Hmm I will close this for now but if I run into it myself I'll fix it.
