### ISSUE TITLE
Remote/server python

### ISSUE THREAD

**Issue by pmcvay** [PythonNut/emacs-config#148]
You left this fantastic answer in stackexchange (https://emacs.stackexchange.com/a/21003/34588). So first, thank you quite a lot for leaving such good answer. 

How would you do the opposite from that question? How would you set up `python-shell-send-region` etc to use a server process while editing a local file? Btw, if you know the answer, I posted the question on stackexchange so if anyone else comes across it, they would be able to find the answer sooner. See https://emacs.stackexchange.com/questions/66783/emacs-python-shell-edit-local-execute-on-server

Thanks!

**Comment by PythonNut** [comment]
Hi! This isn't really the right place for this sort of request. I may give this some thought in the future, but it definitely doesn't fit as an issue with my config. 😉
