### ISSUE TITLE
"<t> is undefined"

### ISSUE THREAD

**Issue by PythonNut** [PythonNut/emacs-config#19]
This error sometimes appears on init after attempting a keybinding, but it's non-deterministic and non-fatal.

**Comment by PythonNut** [comment]
See also: https://github.com/syl20bnr/spacemacs/issues/7855

**Comment by PythonNut** [comment]
Maddeningly enough, I managed to reproduce this, but now that I recompiled some of my files, I no longer can.

**Comment by bjonnh** [comment]
In my case it was due to server-mode. Disabling it solves the problem (but then no more server)

By curiosity what is your OS/interface? Seems that it happens a lot to people using tiling WMs

**Comment by PythonNut** [comment]
@bjonnh I'm using Arch Linux with `xpra` as my WM. Oddly enough, I'm not using `server-mode`. :/

**Comment by bjonnh** [comment]
That's the thing. I have to to M-x server-mode twice to get rid of this problem… And the first time it says it activates the server-mode…

**Comment by PythonNut** [comment]
@bjonnh oh, that's pretty strange. Does that mean it's a but in Emacs itself?

**Comment by PythonNut** [comment]
@bjonnh I gave your suggestion a try (namely, turning `server-mode` on and off) in my config file, but it doesn't seem to have helped.

Strangely enough, I noticed that I can reproduce this 100% of time if I move my Emacs window before pressing a key, and I haven't reproduced it yet in the case where I do not move the window before pressing a key.

**Comment by pakelley** [comment]
Toggling server-mode doesn't work for me, but turning off company does

**Comment by pakelley** [comment]
@PythonNut I'm not actually using your config, but for the passing searching visitor and maybe helping you guys out: toggling server-mode doesn't help for me, but turning off company seems to help. Obviously that's not great, but maybe it's a point in the right direction. :)
