### ISSUE TITLE
Echoe message interrupts message screen

### ISSUE THREAD

**Issue by thorstengrothe** [PythonNut/emacs-config#29]
I copied this to my personal init.file from your config

```
(require 'cl-lib)
(setq gc-cons-threshold 200000000)      ;was 100000000
(cl-letf* (;; In fact, never GC during initialization to save time.
           (gc-cons-threshold most-positive-fixnum)

           ;; Also override load to hide  superfluous loading messages
          ...


  (message "[              ]")
...
(message "[=             ]")
(load-library "thor_themes")
(message "[==            ]")
...
```
it works fine, the message progress bar is shown at startup but interrupet by this message in the minibuffer area:
`Loading bookmarks from ~/.emacs.d/bookmarks...done
[yas] Prepared just-in-time loading of snippets successfully.
`

the message pops up and than loading screen goes on. 
How can I fix this?

P.S. thanks for this great config!!

Regards
Thorsten

**Comment by PythonNut** [comment]
I generally wrap code that produces annoying messages like that with:
```emacs
(cl-letf (((symbol-function 'message)
               (lambda (&rest args)
                 (when args
                   (apply #'format args)))))
      ...
    )
```

This suppresses most messages produced by packages.  If you have a message that isn't correctly suppressed, you'll need to clarify a bit more what's going on.

**Comment by thorstengrothe** [comment]
Ok after this two messages are gone, the following are still shown in echoe area, see here, I think that's clearer. Is there a way to get rid of them?

```
[              ]
[█             ]
[██            ]
Loading bookmarks from ~/.emacs.d/bookmarks...done
[███           ]
Key Chord mode on
[████          ]
[█████         ]
[██████        ]
Cleaning up the recentf list...done (0 removed)
[███████       ]
[yas] Prepared just-in-time loading of snippets successfully.
[████████      ]
[█████████     ]
[██████████    ]
```

**Comment by PythonNut** [comment]
@thorstengrothe I think it would be better to ask general questions on [Emacs.SE](https://emacs.stackexchange.com/).
