### ISSUE TITLE
Silence mc-lists loading

### ISSUE THREAD

**Issue by PythonNut** [PythonNut/emacs-config#31]
I don't want to see

> Loading /home/pythonnut/.emacs.d/data/.mc-lists.el (source)...done

Every single time I load my Emacs.

**Comment by raxod502** [comment]
This doesn't fix the case where multiple-cursors is loaded manually, though, right?

**Comment by PythonNut** [comment]
No, and I can't think of a better way to do it, other than some kind of `with-eval-before-load` system.  `multiple-cursors` seems determined to make this difficult for me.

If you have any better ideas, I'm all ears.

**Comment by raxod502** [comment]
I would have thought that you could just add an advice to the appropriate function that loads `.mc-lists.el`, and the advice would take effect once the function is loaded. I might misunderstand how advices work on not-yet-loaded functions, though.

**Comment by PythonNut** [comment]
The problem here is that the file is not loaded by a function; it's a [toplevel call](https://github.com/magnars/multiple-cursors.el/blob/ddbe3ae932b6564c7429c3b2507510093ed1f3aa/multiple-cursors-core.el#L785).

**Comment by raxod502** [comment]
Well, shoot. I hate top-level calls. You have no idea how much grief I have getting Org-mode to shut up about "can't figure out what version this is" when running it [straight](https://github.com/raxod502/straight.el) from the repository.

So I guess the only real solution is https://github.com/magnars/multiple-cursors.el/pull/290.

**Comment by PythonNut** [comment]
@raxod502 

> You have no idea how much grief I have getting Org-mode to shut up about "can't figure out what version this is" when running it [straight](https://github.com/raxod502/straight.el) from the repository.

I see what you did there.

**Comment by raxod502** [comment]
Indeed. Running packages in an unconventional way seems to have a habit of revealing bugs. For example I had to make a pull request to Magit to deal properly with loading files through symlinks.
