### ISSUE TITLE
Mysterious crashes when editing C/C++

### ISSUE THREAD

**Issue by PythonNut** [PythonNut/emacs-config#90]
Emacs will literally just vanish. No error messages!

May be related to `irony-mode`.

**Comment by PythonNut** [comment]
Confirmed: not caused by `anaconda-mode`.

**Comment by PythonNut** [comment]
Confirmed: not caused by anything in `python-mode` configuration and not caused by `sshfs`.

**Comment by PythonNut** [comment]
Confirmed: not dependent on a specific major mode.

**Comment by PythonNut** [comment]
This has been narrowed down to something in `config-intel`.

**Comment by AsmCoder110** [comment]
How do you figure out modes that aren't the cause of failure? I am having the same problem but with org-mode files. :disappointed:

**Comment by PythonNut** [comment]
For non-deterministic stuff like this, I just disable parts of my configuration. If it's not running then you know it's not to blame. If you can reproduce it reliably within a few days, then you can keep paring the problem scope down until you catch it.

Actually, this was fixed in fff49d8ecbd35b5cd93aaf119b3e27ac2eae28fa, I forgot it also caused this issue along with #92.
